server {
    listen 42727;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://backend:3000;
    }
    location /images/ {
        proxy_pass http://backend:3000;
    }
    location /shared.css {
        proxy_pass http://backend:3000;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
