server {
    listen 42727;
    root /usr/share/nginx/html;
    index index.html;

    resolver 127.0.0.11 valid=30s;

    location /api/ {
        set $backend http://backend:3000;
        proxy_pass $backend;
    }
    location /images/ {
        set $backend http://backend:3000;
        proxy_pass $backend;
    }
    location /shared.css {
        set $backend http://backend:3000;
        proxy_pass $backend;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
